### ISSUE TITLE
Load/Save button missing in geometry designer

### ISSUE THREAD

**Issue by Maarten02** [drarahimi/AERO_Console#1]
Downloaded on may 3 2023 AERO_Console 1.3.0.0
is the Load/Save button deleted intentionally or should it be there?

**Comment by drarahimi** [comment]
@Maarten02  It is deleted intentionally as in the latest version (1.3.0.0) the program automatically loads the currently selected project name from the drop-down list as you switch between the geometry/mass/run files in the window. Does that answer your question?

**Comment by Maarten02** [comment]
Yes, thank you!
